/**
 * 05_classify_lymphocytes.groovy
 * ================================
 * Classifies detected cells as Lymphocytes vs Other based on
 * morphological and staining measurements.
 *
 * Lymphocyte characteristics in H&E:
 *   - Small nucleus (typically 20-80 µm² area)
 *   - Round shape (high circularity > 0.7)
 *   - Intense hematoxylin staining (dark blue)
 *   - Minimal cytoplasm
 *
 * Prerequisites:
 *   - Cell detection completed (script 04)
 *
 * Usage:
 *   - Single image: Script Editor → Run
 *   - All images: Script Editor → Run for project
 */

import qupath.lib.objects.PathObjects
import qupath.lib.objects.classes.PathClass

// ============================================================
// CONFIGURATION — Lymphocyte Classification Thresholds
// ============================================================
// IMPORTANT: These thresholds need to be tuned for each dataset.
// Run script on a pilot slide first and validate visually.
// Adjust thresholds based on Vania's pathology feedback.

// Nucleus area range (µm²) — lymphocytes are small
def minNucleusArea = 15.0
def maxNucleusArea = 80.0

// Nucleus circularity — lymphocytes are round (0-1, 1 = perfect circle)
def minCircularity = 0.65

// Hematoxylin OD (optical density) mean — lymphocytes stain dark
// Calibrated to actual values observed in this dataset (0.07-0.12 range)
def minHematoxylinOD = 0.08

// Maximum cell-to-nucleus area ratio — lymphocytes have minimal cytoplasm
// With 5µm cell expansion, even small cells have ratios of 5-12
// Lymphocytes have smaller cytoplasm so lower ratio than tumor cells
def maxCellNucleusRatio = 7.0

// Solidity threshold — not generated by QuPath 0.6, set to 0 to disable
def minSolidity = 0.0

// ============================================================
// CLASSIFICATION
// ============================================================

def imageData = getCurrentImageData()
if (imageData == null) {
    println "ERROR: No image is open."
    return
}

def detections = getDetectionObjects()
if (detections.isEmpty()) {
    println "ERROR: No cell detections found. Run cell detection first (script 04)."
    return
}

println "Classifying ${detections.size()} cells..."

def lymphocyteClass = PathClass.fromString("Lymphocyte")
def otherClass = PathClass.fromString("Other")

int lymphCount = 0
int otherCount = 0
int skippedCount = 0

detections.each { cell ->
    def measurements = cell.getMeasurements()

    // Get measurements — names depend on QuPath version
    // Try common measurement name patterns
    def nucleusArea = getMeasurement(measurements,
        "Nucleus: Area µm^2", "Nucleus: Area", "Nucleus: Area µm²")
    def circularity = getMeasurement(measurements,
        "Nucleus: Circularity", "Nucleus: Circularity")
    def hematoxylinOD = getMeasurement(measurements,
        "Hematoxylin: Nucleus: Mean", "Nucleus: Hematoxylin OD mean",
        "Hematoxylin: Mean")
    def cellArea = getMeasurement(measurements,
        "Cell: Area µm^2", "Cell: Area", "Cell: Area µm²")
    def solidity = getMeasurement(measurements,
        "Nucleus: Solidity", "Nucleus: Solidity")

    // Skip cells with missing critical measurements
    if (nucleusArea == null || nucleusArea.isNaN()) {
        skippedCount++
        cell.setPathClass(otherClass)
        return
    }

    // Apply classification criteria
    boolean isLymphocyte = true

    // Size check
    if (nucleusArea < minNucleusArea || nucleusArea > maxNucleusArea) {
        isLymphocyte = false
    }

    // Circularity check (if available)
    if (circularity != null && !circularity.isNaN() && circularity < minCircularity) {
        isLymphocyte = false
    }

    // Hematoxylin intensity check (if available)
    if (hematoxylinOD != null && !hematoxylinOD.isNaN() && hematoxylinOD < minHematoxylinOD) {
        isLymphocyte = false
    }

    // Cell:Nucleus ratio check (if available)
    if (cellArea != null && !cellArea.isNaN() && nucleusArea > 0) {
        def ratio = cellArea / nucleusArea
        if (ratio > maxCellNucleusRatio) {
            isLymphocyte = false
        }
    }

    // Solidity check (if available)
    if (solidity != null && !solidity.isNaN() && solidity < minSolidity) {
        isLymphocyte = false
    }

    // Set classification
    if (isLymphocyte) {
        cell.setPathClass(lymphocyteClass)
        lymphCount++
    } else {
        cell.setPathClass(otherClass)
        otherCount++
    }
}

// Update the display
fireHierarchyUpdate()

// ============================================================
// REPORT
// ============================================================

println """
======================================
LYMPHOCYTE CLASSIFICATION RESULTS
======================================
Total cells:       ${detections.size()}
Lymphocytes:       ${lymphCount} (${String.format('%.1f', lymphCount * 100.0 / detections.size())}%)
Other cells:       ${otherCount} (${String.format('%.1f', otherCount * 100.0 / detections.size())}%)
Skipped:           ${skippedCount}

Classification Thresholds Used:
  Nucleus area:       ${minNucleusArea} - ${maxNucleusArea} µm²
  Min circularity:    ${minCircularity}
  Min hematoxylin OD: ${minHematoxylinOD}
  Max cell:nuc ratio: ${maxCellNucleusRatio}
  Min solidity:       ${minSolidity}

VALIDATION:
  - Toggle detections with 'D' key
  - Lymphocytes shown in BLUE, Other in default color
  - Visually verify classification accuracy
  - Adjust thresholds if needed and re-run
======================================
"""

println "Next step: Run script 06 for density quantification."


// ============================================================
// HELPER FUNCTION
// ============================================================

/**
 * Try multiple measurement name variants and return the first match.
 */
def getMeasurement(def measurements, String... names) {
    for (name in names) {
        if (measurements.containsKey(name)) {
            return measurements.get(name)
        }
    }
    return null
}
